#!/bin/sh

MANDARIN="mandarin"
TAIGI="taigi"
HAKKA="hakka"

CHECK_DIALECT ()
(
    dialect="$1"
    [ "$dialect" = "$MANDARIN" ] || [ "$dialect" = "$TAIGI" ] || [ "$dialect" = "$HAKKA" ]
)

HELP_INFO ()
(
    echo "Usage: $0 [dialect]"
    echo ""
    echo "Supported dialect:"
    echo ""
    echo "    taigi"
    echo "    hakka"
)

if ! command -v ocaml-std >/dev/null 2>&1; then
    echo "No ocaml-clean-compile on the system" >&2
    exit 1
fi

dialect="$1"
if [ -z "$dialect" ]; then
    echo "No Chinese dialect" >&2
    HELP_INFO >&2
    exit 1
fi

if ! $(CHECK_DIALECT "$dialect"); then
    echo "Unsupported Chinese dialect: $dialect" >&2
    HELP_INFO >&2
    exit 1
fi

CWD=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || exit 1
if [ "$dialect" = "$MANDARIN" ]; then
    cp "$CWD/mandarin_flag.ml" "$CWD/flag.ml" || exit 1
    cp "$CWD/mandarin_dict.ml" "$CWD/dict.ml" || exit 1
    LEXER="mandarinlr"
elif [ "$dialect" = "$TAIGI" ]; then
    cp "$CWD/taigi_flag.ml" "$CWD/flag.ml" || exit 1
    cp "$CWD/taigi_dict.ml" "$CWD/dict.ml" || exit 1
    LEXER="taigilr"
elif [ "$dialect" = "$HAKKA" ]; then
    cp "$CWD/hakka_flag.ml" "$CWD/flag.ml" || exit 1
    cp "$CWD/hakka_dict.ml" "$CWD/dict.ml" || exit 1
    LEXER="hakkalr"
fi

trap 'rm -f "$CWD/dict.ml" "$CWD/flag.ml"' EXIT INT TERM

$(cd "$CWD" && ocaml-std -o "$LEXER" cli.ml)
