#!/bin/sh

MANDARIN="mandarin"
TAIGI="taigi"
HAKKA="hakka"

CHECK_DIALECT ()
(
    dialect="$1"
    [ "$dialect" = "$MANDARIN" ] || [ "$dialect" = "$TAIGI" ] || [ "$dialect" = "$HAKKA" ]
)

HELP_INFO ()
(
    echo "Usage: $0 [dialect]"
    echo ""
    echo "Supported dialect:"
    echo ""
    echo "    mandarin"
    echo "    taigi"
    echo "    hakka"
)

if ! command -v ocaml-std >/dev/null 2>&1; then
    echo "No ocaml-clean-compile on the system" >&2
    exit 1
fi

dialect="$1"
if [ -z "$dialect" ]; then
    echo "No Chinese dialect" >&2
    HELP_INFO >&2
    exit 1
fi

if ! $(CHECK_DIALECT "$dialect"); then
    echo "Unsupported Chinese dialect: $dialect" >&2
    HELP_INFO >&2
    exit 1
fi

CWD=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || exit 1
cp "$CWD/${dialect}_flag.ml" "$CWD/flag.ml" || exit 1
cp "$CWD/${dialect}_dict.mli" "$CWD/Dict.mli" || exit 1
cp "$CWD/${dialect}_dict.ml" "$CWD/Dict.ml" || exit 1
LEXER="${dialect}lr"

trap 'rm -f "$CWD/Dict.mli" "$CWD/Dict.ml" "$CWD/flag.ml"' EXIT INT TERM

$(cd "$CWD" && ocaml-std -o "$LEXER" Dict.mli Dict.ml cli.ml)
