#!/bin/sh

if ! command -v clean-artifact >/dev/null 2>&1; then
    echo "No clean-artifact on the system" >&2
    exit 1
fi

CWD=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || exit 1
rm -f "$CWD/taigilr.exe" "$CWD/taigilr"
rm -f "$CWD/hakkalr.exe" "$CWD/hakkalr"
