#!/bin/sh

if ! command -v clean-artifact >/dev/null 2>&1; then
    echo "No clean-artifact on the system" >&2
    exit 1
fi

CWD=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || exit 1
for dialect in mandarin taigi hakka; do
    rm -f "$CWD/${dialect}lr.exe" "$CWD/${dialect}lr"
done
